////prototipos////
BYTE sensorPFD(int *carril);
BYTE sensorPFI(int *carril);
BYTE sensorPTD(int *carril);
BYTE sensorPTI(int *carril);
BYTE sensorPLD(int *carril);
BYTE sensorPLI(int *carril);
BYTE sensor_Nivel_bateria(Sas *This);
BYTE sensor_Velocidad(Sas *This);
BYTE sensor_freno(Sas *This);
BYTE acelerador(Sas *This);
BYTE Freno(Sas *This);
BYTE Direccion(Sas *This);
BYTE ON_OFF(Sas *This);
void printIP(unsigned long int ip);
int llena_archivo();
int lee_archivo(Sas DEV[LEN_SAS]);
int inicializa_funciones();
void imprime(Sas *dev);
void imprime_pista();
void print_car(int *carril,int *altura);
void desprintcar(int *carril,int *altura);
void mueve(int *carril,int *altura);
void mueve_derecha(int *carril, int *altura);
void mueve_izquierda(int *carril, int *altura);
void mueve_arriba(int *carril, int *altura);
void mueve_abajo(int *carril, int *altura);
void recorre_pista();
void velocidad();
void invierte_M();
void acelerador_screen();
void aguja(int speed);
void remove_agujas();
void static_car();
void valida_choque(int *carril);
void paint_sensor_derecho_frontal();
void paint_sensor_izquierdo_Frontal();
void paint_sensor_izquierdo();
void paint_sensor_derecho();
void paint_sensor_abajo_derecho();
void paint_sensor_abajo_izquierdo();
void imprime_sensores();
void paint_sensor_derecho_frontal_active();
void paint_sensor_izquierdo_Frontal_active();
void paint_sensor_izquierdo_active();
void paint_sensor_derecho_active();
void paint_sensor_abajo_derecho_active();
void paint_sensor_abajo_izquierdo_active();
void valida_active_PFD(int *carril);
void valida_active_PFI(int *carril);
void imprime_sensores_active();
void valida_Sensores(int *carril);
void valida_actives(int *carril);
///////////////////////////////////////////////////////
